package GUI;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Parameter;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/** Ventana de muestra de metodos, constructores y atributos.
 * @author Fabrizio
 * @author www.LoweWriter.com
*/
public class infoClass extends javax.swing.JFrame {

    /**
     * Muestra en texto la informacion de la ventana
     * @return el string con la informacion
     */
    @Override
    public String toString() {
        return "infoClass{" + "jScrollPane1=" + jScrollPane1 + ", jScrollPane2=" + jScrollPane2 + ", jScrollPane3=" + jScrollPane3 + ", tablaAtrib=" + tablaAtrib + ", tablaConstu=" + tablaConstu + ", tablaMet=" + tablaMet + '}';
    }

    /**
     * Crea una nueva ventana infoClass
     */
    public infoClass() {
        initComponents();
    }

    /**
     * Rellena las tablas con la informacion de la clase 
     * @param clase la clase cuya informacion se muestra en la tabla
     */
    public void fillTable(Class clase){
        DefaultTableModel tabla = (DefaultTableModel) tablaConstu.getModel();
        tabla.setRowCount(0);
        Constructor[] constructores=clase.getConstructors();
        for(Constructor construc:constructores)
        {
            ArrayList<Object> fila=new ArrayList<Object>();
            fila.add(construc.getName());
            Parameter[] para=construc.getParameters();
            String param="";
            for(Parameter parametro:para)
            {
                param=param+" "+parametro.getType().getSimpleName().toString();
            }
            fila.add(param);
            Object[]filaConv=fila.toArray();
            tabla.addRow(filaConv); 
        }
        DefaultTableModel tabla2 = (DefaultTableModel) tablaMet.getModel();
        tabla2.setRowCount(0);
        Method[] metodos=clase.getMethods();
        for(Method metodo:metodos)
        {
            ArrayList<Object> fila=new ArrayList<Object>();
            fila.add(metodo.getName());
            fila.add(Modifier.toString(metodo.getModifiers()));
            fila.add(metodo.getReturnType().getSimpleName());
            Parameter[] para=metodo.getParameters();
            String param="";
            for(Parameter parametro:para)
            {
                param=param+" "+parametro.getType().getSimpleName().toString();
            }
            fila.add(param);
            Object[]filaConv=fila.toArray();
            tabla2.addRow(filaConv);
        }
        DefaultTableModel tabla3 = (DefaultTableModel) tablaAtrib.getModel();
        tabla3.setRowCount(0);
        Field[] atributos=clase.getFields();
        for(Field atributo:atributos)
        {
            ArrayList<Object> fila=new ArrayList<Object>();
            fila.add(atributo.getName());
            fila.add(Modifier.toString(atributo.getModifiers()));
            fila.add(atributo.getType().getSimpleName());
            Object[]filaConv=fila.toArray();
            tabla3.addRow(filaConv);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConstu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAtrib = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaConstu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre ", "parametros"
            }
        ));
        jScrollPane1.setViewportView(tablaConstu);

        tablaAtrib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Modoficadores", "Tipos"
            }
        ));
        jScrollPane2.setViewportView(tablaAtrib);

        tablaMet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Modificadores", "Return", "Parametros"
            }
        ));
        jScrollPane3.setViewportView(tablaMet);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Constructores, metodos y atributos ");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Atributos (Publicos)");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Metodos");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Constructores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(272, 272, 272))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(239, 239, 239))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaAtrib;
    private javax.swing.JTable tablaConstu;
    private javax.swing.JTable tablaMet;
    // End of variables declaration//GEN-END:variables
}
